#' Custom Print for Select_BayTetra Class
#'
#' Print the model selection result
#'
#' @param x An object of class "Select_BayTetra", a named list containing the elpd values, name is the degree of freedom. The object is
#' generated by "Model_selection_BayTetra()"
#' @param ... Additional arguments passed to the base print function (usually not used).
#'
#' @examples
#' \dontrun{
#' selection_result = Model_selection_BayTetra(
#'                          df_min = 4, df_max = 6,
#'                          data = df_new,
#'                          v_rsp = paste("R", 1:2, sep = ""),
#'                          v_covs = "cov1",
#'                          v_grp = "Group",
#'                          v_time = "time"
#'                          )
#' print(selection_result[[1]])
#'
#' }
#'
#' @seealso [Model_selection_BayTetra()]
#'
#' @noRd
print.Select_BayTetra <- function(x, ...) {
  print.default(x)
  highest_df <- attr(x, "highest_df")
  cat("The maximum elpd is reached at df =", highest_df, "\n")
}

