# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
NULL

#' @noRd
NULL

#' @importFrom Rcpp sourceCpp
NULL

#' @importFrom Rcpp sourceCpp
#' @noRd
NULL

dmvn_rcpp <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_BayTetra_dmvn_rcpp`, x, mean, sigma, logd)
}

rmvn_rcpp <- function(n, mean, sigma) {
    .Call(`_BayTetra_rmvn_rcpp`, n, mean, sigma)
}

#' @noRd
rinvgamma_rcpp <- function(a, b) {
    .Call(`_BayTetra_rinvgamma_rcpp`, a, b)
}

#' @noRd
update_alpha_cpp <- function(beta, omega, sigma2, data_index, y, B, Z, g, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha) {
    .Call(`_BayTetra_update_alpha_cpp`, beta, omega, sigma2, data_index, y, B, Z, g, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha)
}

#' @noRd
update_eta_kq_cpp <- function(alpha, beta, omega, sigma2, beta_kq0, xi, gamma_kq, nu_kq, y, Z, B, g_cpp, data_index) {
    .Call(`_BayTetra_update_eta_kq_cpp`, alpha, beta, omega, sigma2, beta_kq0, xi, gamma_kq, nu_kq, y, Z, B, g_cpp, data_index)
}

#' @noRd
update_xi_kq_cpp <- function(alpha, beta, omega, sigma2, beta_kq0, eta, m, g_cpp, data_index, y, Z, B) {
    .Call(`_BayTetra_update_xi_kq_cpp`, alpha, beta, omega, sigma2, beta_kq0, eta, m, g_cpp, data_index, y, Z, B)
}

#' @noRd
update_beta_kq0_cpp <- function(alpha, beta, omega, sigma2, gamma_kq0, nu_kq0, y, Z, B, g_cpp, data_index) {
    .Call(`_BayTetra_update_beta_kq0_cpp`, alpha, beta, omega, sigma2, gamma_kq0, nu_kq0, y, Z, B, g_cpp, data_index)
}

logpost_omega_cpp <- function(i, omega_i, alpha, beta, sigma2, Sigma_omega, y, Z, B, g, data_index, K, Q, J_max) {
    .Call(`_BayTetra_logpost_omega_cpp`, i, omega_i, alpha, beta, sigma2, Sigma_omega, y, Z, B, g, data_index, K, Q, J_max)
}

#' @noRd
update_omega_cpp <- function(alpha, beta, omega, sigma2, Sigma_omega, y, Z, B, g, data_index, omega_var_update = 0.04) {
    .Call(`_BayTetra_update_omega_cpp`, alpha, beta, omega, sigma2, Sigma_omega, y, Z, B, g, data_index, omega_var_update)
}

logpost_Sigma_omega_cpp <- function(Sigma_omega, omega) {
    .Call(`_BayTetra_logpost_Sigma_omega_cpp`, Sigma_omega, omega)
}

#' @noRd
update_Sigma_omega_cpp <- function(omega, Sigma_omega, Sigma_omega_step = 0.008) {
    .Call(`_BayTetra_update_Sigma_omega_cpp`, omega, Sigma_omega, Sigma_omega_step)
}

update_sigma2_cpp <- function(alpha, beta, omega, y, Z, B, data_index, g, h_1, h_2) {
    .Call(`_BayTetra_update_sigma2_cpp`, alpha, beta, omega, y, Z, B, data_index, g, h_1, h_2)
}

