#' Summarize Results of BayTetra Hypothesis Test
#'
#' Summarize result generated by the `Test_BayTetra` function in a tidy way
#'
#' @param object An object of class "Test_BayTetra", typically the result of calling "Test_BayTetra()".
#' @param ... Additional arguments affecting the summary produced (currently not used).

#' @return The function print the object.
#'
#' @examples
#' \dontrun{
#' test_result <- Test_BayTetra(mcmc_result,
#'                            v_Rsp = paste("R", 1:2,sep = ""))
#' summary(test_result)
#' }
#'
#' @seealso
#' \code{\link{Test_BayTetra}} The function that generates the "Test_BayTetra" object.
#'
#' @export

summary.Test_BayTetra <- function(object,...) {
  # Customize how the object should be summarized
  cat("Hypothesis testing summary of BayTetra\n")
  cat("----------------------------\n")

  cat("\nBayTetra_summary\n")
  print(object$BayTetra_summary)
  cat("----------------------------\n")

  cat("\npairwise_significance\n")
  # Remove quotes
  no_quotes_matrix <- matrix(sapply(object$pairwise_significance, function(x) gsub("\"", "", x)),
                             ncol = ncol(object$pairwise_significance),
                             nrow = nrow(object$pairwise_significance))

  # Assign column and row names
  colnames(no_quotes_matrix) <- colnames(object$pairwise_significance)
  rownames(no_quotes_matrix) <- rownames(object$pairwise_significance)

  print(no_quotes_matrix)
  cat("----------------------------\n")

  cat("\ntesting trajectory differences among all the groups\n")
  print(object$diff_among_all_grps)
  cat("----------------------------\n")
}


