// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmvn_rcpp
double dmvn_rcpp(const arma::rowvec& x, const arma::rowvec& mean, const arma::mat& sigma, bool logd);
RcppExport SEXP _BayTetra_dmvn_rcpp(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvn_rcpp(x, mean, sigma, logd));
    return rcpp_result_gen;
END_RCPP
}
// rmvn_rcpp
arma::mat rmvn_rcpp(const int n, const arma::vec& mean, const arma::mat& sigma);
RcppExport SEXP _BayTetra_rmvn_rcpp(SEXP nSEXP, SEXP meanSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvn_rcpp(n, mean, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rinvgamma_rcpp
double rinvgamma_rcpp(double a, double b);
RcppExport SEXP _BayTetra_rinvgamma_rcpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rinvgamma_rcpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// update_alpha_cpp
arma::mat update_alpha_cpp(const arma::cube& beta, const arma::mat& omega, const arma::vec& sigma2, const arma::cube& data_index, const arma::cube& y, const arma::field<arma::cube>& B, const arma::field<arma::cube>& Z, const arma::vec& g, const arma::cube& Z_sum, const arma::mat& V_alpha_inv, const arma::vec& V_alpha_inv_mu_alpha);
RcppExport SEXP _BayTetra_update_alpha_cpp(SEXP betaSEXP, SEXP omegaSEXP, SEXP sigma2SEXP, SEXP data_indexSEXP, SEXP ySEXP, SEXP BSEXP, SEXP ZSEXP, SEXP gSEXP, SEXP Z_sumSEXP, SEXP V_alpha_invSEXP, SEXP V_alpha_inv_mu_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Z_sum(Z_sumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V_alpha_inv(V_alpha_invSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V_alpha_inv_mu_alpha(V_alpha_inv_mu_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_alpha_cpp(beta, omega, sigma2, data_index, y, B, Z, g, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha));
    return rcpp_result_gen;
END_RCPP
}
// update_eta_kq_cpp
arma::mat update_eta_kq_cpp(const arma::mat& alpha, const arma::cube& beta, const arma::mat& omega, const arma::vec& sigma2, const arma::mat& beta_kq0, const arma::cube& xi, const arma::mat& gamma_kq, const arma::mat& nu_kq, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B, const arma::vec& g_cpp, const arma::cube& data_index);
RcppExport SEXP _BayTetra_update_eta_kq_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP, SEXP sigma2SEXP, SEXP beta_kq0SEXP, SEXP xiSEXP, SEXP gamma_kqSEXP, SEXP nu_kqSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP, SEXP g_cppSEXP, SEXP data_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_kq0(beta_kq0SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type gamma_kq(gamma_kqSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type nu_kq(nu_kqSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g_cpp(g_cppSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(update_eta_kq_cpp(alpha, beta, omega, sigma2, beta_kq0, xi, gamma_kq, nu_kq, y, Z, B, g_cpp, data_index));
    return rcpp_result_gen;
END_RCPP
}
// update_xi_kq_cpp
arma::cube update_xi_kq_cpp(const arma::mat& alpha, const arma::cube& beta, const arma::mat& omega, const arma::vec& sigma2, const arma::mat& beta_kq0, const arma::mat& eta, const arma::cube& m, const arma::vec& g_cpp, const arma::cube& data_index, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B);
RcppExport SEXP _BayTetra_update_xi_kq_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP, SEXP sigma2SEXP, SEXP beta_kq0SEXP, SEXP etaSEXP, SEXP mSEXP, SEXP g_cppSEXP, SEXP data_indexSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_kq0(beta_kq0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g_cpp(g_cppSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(update_xi_kq_cpp(alpha, beta, omega, sigma2, beta_kq0, eta, m, g_cpp, data_index, y, Z, B));
    return rcpp_result_gen;
END_RCPP
}
// update_beta_kq0_cpp
arma::mat update_beta_kq0_cpp(const arma::mat& alpha, const arma::cube& beta, const arma::mat& omega, const arma::vec& sigma2, const arma::mat& gamma_kq0, const arma::mat& nu_kq0, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B, const arma::vec& g_cpp, const arma::cube& data_index);
RcppExport SEXP _BayTetra_update_beta_kq0_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP, SEXP sigma2SEXP, SEXP gamma_kq0SEXP, SEXP nu_kq0SEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP, SEXP g_cppSEXP, SEXP data_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type gamma_kq0(gamma_kq0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type nu_kq0(nu_kq0SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g_cpp(g_cppSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(update_beta_kq0_cpp(alpha, beta, omega, sigma2, gamma_kq0, nu_kq0, y, Z, B, g_cpp, data_index));
    return rcpp_result_gen;
END_RCPP
}
// logpost_omega_cpp
double logpost_omega_cpp(int i, const arma::rowvec& omega_i, const arma::mat& alpha, const arma::cube& beta, const arma::vec& sigma2, const arma::mat& Sigma_omega, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B, const arma::vec& g, const arma::cube& data_index, int K, int Q, int J_max);
RcppExport SEXP _BayTetra_logpost_omega_cpp(SEXP iSEXP, SEXP omega_iSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP sigma2SEXP, SEXP Sigma_omegaSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP, SEXP gSEXP, SEXP data_indexSEXP, SEXP KSEXP, SEXP QSEXP, SEXP J_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type omega_i(omega_iSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_omega(Sigma_omegaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type J_max(J_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(logpost_omega_cpp(i, omega_i, alpha, beta, sigma2, Sigma_omega, y, Z, B, g, data_index, K, Q, J_max));
    return rcpp_result_gen;
END_RCPP
}
// update_omega_cpp
arma::mat update_omega_cpp(const arma::mat& alpha, const arma::cube& beta, const arma::mat& omega, const arma::vec& sigma2, const arma::mat& Sigma_omega, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B, const arma::vec& g, const arma::cube& data_index, const double omega_var_update);
RcppExport SEXP _BayTetra_update_omega_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP, SEXP sigma2SEXP, SEXP Sigma_omegaSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP, SEXP gSEXP, SEXP data_indexSEXP, SEXP omega_var_updateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_omega(Sigma_omegaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< const double >::type omega_var_update(omega_var_updateSEXP);
    rcpp_result_gen = Rcpp::wrap(update_omega_cpp(alpha, beta, omega, sigma2, Sigma_omega, y, Z, B, g, data_index, omega_var_update));
    return rcpp_result_gen;
END_RCPP
}
// logpost_Sigma_omega_cpp
double logpost_Sigma_omega_cpp(const arma::mat& Sigma_omega, const arma::mat& omega);
RcppExport SEXP _BayTetra_logpost_Sigma_omega_cpp(SEXP Sigma_omegaSEXP, SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_omega(Sigma_omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(logpost_Sigma_omega_cpp(Sigma_omega, omega));
    return rcpp_result_gen;
END_RCPP
}
// update_Sigma_omega_cpp
arma::mat update_Sigma_omega_cpp(const arma::mat& omega, const arma::mat& Sigma_omega, const double Sigma_omega_step);
RcppExport SEXP _BayTetra_update_Sigma_omega_cpp(SEXP omegaSEXP, SEXP Sigma_omegaSEXP, SEXP Sigma_omega_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_omega(Sigma_omegaSEXP);
    Rcpp::traits::input_parameter< const double >::type Sigma_omega_step(Sigma_omega_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Sigma_omega_cpp(omega, Sigma_omega, Sigma_omega_step));
    return rcpp_result_gen;
END_RCPP
}
// update_sigma2_cpp
arma::vec update_sigma2_cpp(arma::mat& alpha, arma::cube& beta, arma::mat& omega, const arma::cube& y, const arma::field<arma::cube>& Z, const arma::field<arma::cube>& B, const arma::cube& data_index, const arma::vec& g, double h_1, double h_2);
RcppExport SEXP _BayTetra_update_sigma2_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP omegaSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP BSEXP, SEXP data_indexSEXP, SEXP gSEXP, SEXP h_1SEXP, SEXP h_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type data_index(data_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type h_1(h_1SEXP);
    Rcpp::traits::input_parameter< double >::type h_2(h_2SEXP);
    rcpp_result_gen = Rcpp::wrap(update_sigma2_cpp(alpha, beta, omega, y, Z, B, data_index, g, h_1, h_2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayTetra_dmvn_rcpp", (DL_FUNC) &_BayTetra_dmvn_rcpp, 4},
    {"_BayTetra_rmvn_rcpp", (DL_FUNC) &_BayTetra_rmvn_rcpp, 3},
    {"_BayTetra_rinvgamma_rcpp", (DL_FUNC) &_BayTetra_rinvgamma_rcpp, 2},
    {"_BayTetra_update_alpha_cpp", (DL_FUNC) &_BayTetra_update_alpha_cpp, 11},
    {"_BayTetra_update_eta_kq_cpp", (DL_FUNC) &_BayTetra_update_eta_kq_cpp, 13},
    {"_BayTetra_update_xi_kq_cpp", (DL_FUNC) &_BayTetra_update_xi_kq_cpp, 12},
    {"_BayTetra_update_beta_kq0_cpp", (DL_FUNC) &_BayTetra_update_beta_kq0_cpp, 11},
    {"_BayTetra_logpost_omega_cpp", (DL_FUNC) &_BayTetra_logpost_omega_cpp, 14},
    {"_BayTetra_update_omega_cpp", (DL_FUNC) &_BayTetra_update_omega_cpp, 11},
    {"_BayTetra_logpost_Sigma_omega_cpp", (DL_FUNC) &_BayTetra_logpost_Sigma_omega_cpp, 2},
    {"_BayTetra_update_Sigma_omega_cpp", (DL_FUNC) &_BayTetra_update_Sigma_omega_cpp, 3},
    {"_BayTetra_update_sigma2_cpp", (DL_FUNC) &_BayTetra_update_sigma2_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayTetra(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
