# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
NULL

#' @noRd
NULL

#' @importFrom Rcpp sourceCpp
NULL

dmvn_rcpp <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_BayTetra_dmvn_rcpp`, x, mean, sigma, logd)
}

#' @noRd
Generate_t_cpp <- function(I, Q, J_max, min_dist, lower, upper, data_index) {
    .Call(`_BayTetra_Generate_t_cpp`, I, Q, J_max, min_dist, lower, upper, data_index)
}

rmvn_rcpp <- function(n, mean, sigma) {
    .Call(`_BayTetra_rmvn_rcpp`, n, mean, sigma)
}

#' @noRd
rinvgamma_rcpp <- function(a, b) {
    .Call(`_BayTetra_rinvgamma_rcpp`, a, b)
}

#' @noRd
dinv_gamma_rcpp <- function(x, alpha, beta, logd = FALSE) {
    .Call(`_BayTetra_dinv_gamma_rcpp`, x, alpha, beta, logd)
}

#' @noRd
update_alpha_cpp <- function(beta, beta_kq0, omega, theta_iq, sigma2, y, data_index, B, Z, g_cpp, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha) {
    .Call(`_BayTetra_update_alpha_cpp`, beta, beta_kq0, omega, theta_iq, sigma2, y, data_index, B, Z, g_cpp, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha)
}

#' @noRd
update_beta_kq0_cpp <- function(alpha, beta, omega, theta_iq, sigma2, nu_kq0, y, data_index, B, Z, g_cpp) {
    .Call(`_BayTetra_update_beta_kq0_cpp`, alpha, beta, omega, theta_iq, sigma2, nu_kq0, y, data_index, B, Z, g_cpp)
}

#' @noRd
update_beta_kq_cpp <- function(alpha, beta, beta_kq0, omega, theta_iq, sigma2, y, data_index, K_mat, tau_kq2, B, Z, g_cpp) {
    .Call(`_BayTetra_update_beta_kq_cpp`, alpha, beta, beta_kq0, omega, theta_iq, sigma2, y, data_index, K_mat, tau_kq2, B, Z, g_cpp)
}

#' @noRd
logpost_omega_cpp <- function(i, omega_i, alpha, beta, beta_kq0, theta_iq, sigma2, Sigma_omega, y, data_index, B, Z, g_cpp, K, Q, J_max) {
    .Call(`_BayTetra_logpost_omega_cpp`, i, omega_i, alpha, beta, beta_kq0, theta_iq, sigma2, Sigma_omega, y, data_index, B, Z, g_cpp, K, Q, J_max)
}

#' @noRd
update_omega_cpp <- function(alpha, beta, beta_kq0, omega, theta_iq, sigma2, Sigma_omega, y, data_index, B, Z, g_cpp, omega_var_update = 0.04) {
    .Call(`_BayTetra_update_omega_cpp`, alpha, beta, beta_kq0, omega, theta_iq, sigma2, Sigma_omega, y, data_index, B, Z, g_cpp, omega_var_update)
}

#' @noRd
logpost_Sigma_omega_cpp <- function(Sigma_omega, omega) {
    .Call(`_BayTetra_logpost_Sigma_omega_cpp`, Sigma_omega, omega)
}

#' @noRd
update_Sigma_omega_cpp <- function(omega, Sigma_omega, Sigma_omega_step = 0.008) {
    .Call(`_BayTetra_update_Sigma_omega_cpp`, omega, Sigma_omega, Sigma_omega_step)
}

#' @noRd
update_theta_iq_cpp <- function(alpha, beta, beta_kq0, omega, sigma2, y, data_index, t_std, t_org, B, Z, g_cpp, tau_q_vec, lambda_q_vec) {
    .Call(`_BayTetra_update_theta_iq_cpp`, alpha, beta, beta_kq0, omega, sigma2, y, data_index, t_std, t_org, B, Z, g_cpp, tau_q_vec, lambda_q_vec)
}

#' @noRd
update_tau_q_cpp <- function(theta_iq, a_tau, b_tau, data_index, t, lambda_q_vec) {
    .Call(`_BayTetra_update_tau_q_cpp`, theta_iq, a_tau, b_tau, data_index, t, lambda_q_vec)
}

#' @noRd
logpost_lambda_normpart_cpp <- function(q, theta_iq, lambda_q, tau_q, data_index, t) {
    .Call(`_BayTetra_logpost_lambda_normpart_cpp`, q, theta_iq, lambda_q, tau_q, data_index, t)
}

#' @importFrom Rcpp sourceCpp
#' @noRd
update_lambda_q_cpp <- function(lambda, a_lam, b_lam, theta_iq, tau_q_vec, data_index, t, lambda_step = 0.1) {
    .Call(`_BayTetra_update_lambda_q_cpp`, lambda, a_lam, b_lam, theta_iq, tau_q_vec, data_index, t, lambda_step)
}

#' @noRd
update_lambda_q_cpp_wth_accept <- function(lambda, a_lam, b_lam, theta_iq, tau_q_vec, data_index, t, lambda_step = 0.1) {
    .Call(`_BayTetra_update_lambda_q_cpp_wth_accept`, lambda, a_lam, b_lam, theta_iq, tau_q_vec, data_index, t, lambda_step)
}

#' @noRd
update_sigma2_cpp <- function(alpha, beta, beta_kq0, omega, theta_iq, y, data_index, B, Z, g_cpp, h_1, h_2) {
    .Call(`_BayTetra_update_sigma2_cpp`, alpha, beta, beta_kq0, omega, theta_iq, y, data_index, B, Z, g_cpp, h_1, h_2)
}

#' @noRd
update_alpha_Q1_cpp <- function(beta, sigma2, data_index, y, B, Z, g, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha) {
    .Call(`_BayTetra_update_alpha_Q1_cpp`, beta, sigma2, data_index, y, B, Z, g, Z_sum, V_alpha_inv, V_alpha_inv_mu_alpha)
}

#' @noRd
update_eta_kq_Q1_cpp <- function(alpha, beta, sigma2, beta_kq0, xi, gamma_kq, nu_kq, y, Z, B, g_cpp, data_index) {
    .Call(`_BayTetra_update_eta_kq_Q1_cpp`, alpha, beta, sigma2, beta_kq0, xi, gamma_kq, nu_kq, y, Z, B, g_cpp, data_index)
}

#' @noRd
update_xi_kq_Q1_cpp <- function(alpha, beta, sigma2, beta_kq0, eta, m, g_cpp, data_index, y, Z, B) {
    .Call(`_BayTetra_update_xi_kq_Q1_cpp`, alpha, beta, sigma2, beta_kq0, eta, m, g_cpp, data_index, y, Z, B)
}

#' @noRd
update_beta_kq0_Q1_cpp <- function(alpha, beta, sigma2, gamma_kq0, nu_kq0, y, Z, B, g_cpp, data_index) {
    .Call(`_BayTetra_update_beta_kq0_Q1_cpp`, alpha, beta, sigma2, gamma_kq0, nu_kq0, y, Z, B, g_cpp, data_index)
}

#' @noRd
update_sigma2_Q1_cpp <- function(alpha, beta, y, Z, B, data_index, g, h_1, h_2) {
    .Call(`_BayTetra_update_sigma2_Q1_cpp`, alpha, beta, y, Z, B, data_index, g, h_1, h_2)
}

